name: Docker Compose Build

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
      

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose build
        
      - name: Push Docker images to GitHub Container Registry
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/VELEX-Back:$(( $(date +%s) / 60 / 60 / 24 ))
          docker push $IMAGE_NAME
